services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-net

networks:
  app-net:
    external: true