worker_processes auto;

env AWS_ACCESS_KEY_ID;
env AWS_SECRET_ACCESS_KEY;
env AWS_REGION;

events {
    worker_connections 1024;
}

http {

    lua_package_path
        "/usr/local/openresty/site/lualib/?.lua;/etc/nginx/lua/?.lua;;";

    resolver 127.0.0.11 ipv6=off;

    server {

        listen 80;

        location /hls/ {

            secure_link $arg_md5,$arg_expires;
            secure_link_md5
                "$secure_link_expires$uri mysecret";

            if ($secure_link = "") {
                return 403;
            }

            if ($secure_link = "0") {
                return 410;
            }

            rewrite ^/hls/(.*)$ /media/$1 break;

            access_by_lua_file /etc/nginx/lua/aws_sign.lua;

            proxy_set_header Host minio;

            proxy_pass http://minio:9000;

            proxy_buffering off;
            
            proxy_request_buffering off;    
        }
    }
}